-- MySQL Script generated by MySQL Workbench
-- Mon May 26 21:15:06 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_library` DEFAULT CHARACTER SET utf8 ;
USE `db_library` ;

-- -----------------------------------------------------
-- Table `db_library`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`User` (
  `ID_User` CHAR(10) NOT NULL,
  `Nama_User` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` CHAR(100) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_User`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_library`.`Anggota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`Anggota` (
  `ID_Anggota` CHAR(10) NOT NULL,
  `Nama_Anggota` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telepon` VARCHAR(15) NOT NULL,
  `Tanggal_Bergabung` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Anggota`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_library`.`Kategori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`Kategori` (
  `ID_Kategori` CHAR(10) NOT NULL,
  `Nama_Kategori` VARCHAR(45) NOT NULL,
  `Deskripsi_Kategori` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Kategori`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_library`.`Penerbit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`Penerbit` (
  `ID_Penerbit` CHAR(10) NOT NULL,
  `Nama_Penerbit` VARCHAR(45) NULL,
  `Situs_Penerbit` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Penerbit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_library`.`Buku`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`Buku` (
  `ID_Buku` CHAR(10) NOT NULL,
  `Judul_Buku` VARCHAR(45) NOT NULL,
  `Pengarang_Buku` VARCHAR(45) NOT NULL,
  `Tahun_Terbit` VARCHAR(10) NOT NULL,
  `ID_Kategori` CHAR(10) NOT NULL,
  `ID_Penerbit` CHAR(10) NOT NULL,
  PRIMARY KEY (`ID_Buku`),
  INDEX `fk_Buku_Kategori1_idx` (`ID_Kategori` ASC) VISIBLE,
  INDEX `fk_Buku_Penerbit1_idx` (`ID_Penerbit` ASC) VISIBLE,
  CONSTRAINT `fk_Buku_Kategori1`
    FOREIGN KEY (`ID_Kategori`)
    REFERENCES `db_library`.`Kategori` (`ID_Kategori`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Buku_Penerbit1`
    FOREIGN KEY (`ID_Penerbit`)
    REFERENCES `db_library`.`Penerbit` (`ID_Penerbit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_library`.`Peminjaman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`Peminjaman` (
  `ID_Peminjaman` CHAR(10) NOT NULL,
  `Tanggal_Peminjaman` DATE NULL,
  `Tanggal_Pengembalian` DATE NULL,
  `Status_Peminjaman` VARCHAR(45) NULL,
  `ID_User` CHAR(10) NOT NULL,
  `ID_Anggota` CHAR(10) NOT NULL,
  PRIMARY KEY (`ID_Peminjaman`),
  INDEX `fk_Peminjaman_User_idx` (`ID_User` ASC) VISIBLE,
  UNIQUE INDEX `Tanggal_Pengembalian_UNIQUE` (`Tanggal_Pengembalian` ASC) VISIBLE,
  INDEX `fk_Peminjaman_Anggota1_idx` (`ID_Anggota` ASC) VISIBLE,
  CONSTRAINT `fk_Peminjaman_User`
    FOREIGN KEY (`ID_User`)
    REFERENCES `db_library`.`User` (`ID_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peminjaman_Anggota1`
    FOREIGN KEY (`ID_Anggota`)
    REFERENCES `db_library`.`Anggota` (`ID_Anggota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_library`.`Pengembalian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`Pengembalian` (
  `ID_Pengembalian` CHAR(10) NOT NULL,
  `Tanggal_Pengembalian` DATE NULL,
  `Denda_Pengembalian` DOUBLE NULL,
  `ID_Peminjaman` CHAR(10) NOT NULL,
  `ID_Anggota` CHAR(10) NOT NULL,
  PRIMARY KEY (`ID_Pengembalian`),
  INDEX `fk_Pengembalian_Peminjaman1_idx` (`ID_Peminjaman` ASC) VISIBLE,
  INDEX `fk_Pengembalian_Anggota1_idx` (`ID_Anggota` ASC) VISIBLE,
  CONSTRAINT `fk_Pengembalian_Peminjaman1`
    FOREIGN KEY (`ID_Peminjaman`)
    REFERENCES `db_library`.`Peminjaman` (`ID_Peminjaman`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pengembalian_Anggota1`
    FOREIGN KEY (`ID_Anggota`)
    REFERENCES `db_library`.`Anggota` (`ID_Anggota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_library`.`Detail_Pengembalian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`Detail_Pengembalian` (
  `ID_Pengembalian` CHAR(10) NOT NULL,
  `ID_Buku` CHAR(10) NOT NULL,
  `Jumlah_Denda` DOUBLE NULL,
  PRIMARY KEY (`ID_Pengembalian`, `ID_Buku`),
  INDEX `fk_Detail_Pengembalian_Buku1_idx` (`ID_Buku` ASC) VISIBLE,
  CONSTRAINT `fk_Detail_Pengembalian_Pengembalian1`
    FOREIGN KEY (`ID_Pengembalian`)
    REFERENCES `db_library`.`Pengembalian` (`ID_Pengembalian`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detail_Pengembalian_Buku1`
    FOREIGN KEY (`ID_Buku`)
    REFERENCES `db_library`.`Buku` (`ID_Buku`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_library`.`Detail_Peminjaman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`Detail_Peminjaman` (
  `ID_Peminjaman` CHAR(10) NOT NULL,
  `ID_Buku` CHAR(10) NOT NULL,
  `Status_Pengembalian` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Peminjaman`),
  INDEX `fk_Detail_Peminjaman_Buku1_idx` (`ID_Buku` ASC) VISIBLE,
  UNIQUE INDEX `Status_Pengembalian_UNIQUE` (`Status_Pengembalian` ASC) VISIBLE,
  CONSTRAINT `fk_Detail_Peminjaman_Peminjaman1`
    FOREIGN KEY (`ID_Peminjaman`)
    REFERENCES `db_library`.`Peminjaman` (`ID_Peminjaman`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detail_Peminjaman_Buku1`
    FOREIGN KEY (`ID_Buku`)
    REFERENCES `db_library`.`Buku` (`ID_Buku`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_library`.`Sementara`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`Sementara` (
  `ID_Buku` CHAR(10) NOT NULL,
  INDEX `fk_Sementara_Buku1_idx` (`ID_Buku` ASC) VISIBLE,
  CONSTRAINT `fk_Sementara_Buku1`
    FOREIGN KEY (`ID_Buku`)
    REFERENCES `db_library`.`Buku` (`ID_Buku`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
