/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author ECAA
 */
public class MenuDashboard extends javax.swing.JPanel {

    /**
     * Creates new form MenuDashboard
     */
    public MenuDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cardAnggota = new javax.swing.JPanel();
        lb_anggota = new javax.swing.JLabel();
        lb_jumlahAnggota = new javax.swing.JLabel();
        lb_iconAnggota = new javax.swing.JLabel();
        cardAnggota3 = new javax.swing.JPanel();
        lb_anggota3 = new javax.swing.JLabel();
        lb_jumlahAnggota3 = new javax.swing.JLabel();
        lb_iconAnggota3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cardAnggota4 = new javax.swing.JPanel();
        lb_anggota4 = new javax.swing.JLabel();
        lb_jumlahAnggota4 = new javax.swing.JLabel();
        lb_iconAnggota4 = new javax.swing.JLabel();
        cardAnggota5 = new javax.swing.JPanel();
        lb_anggota5 = new javax.swing.JLabel();
        lb_jumlahAnggota5 = new javax.swing.JLabel();
        lb_iconAnggota5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(831, 720));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(831, 720));

        cardAnggota.setBackground(new java.awt.Color(153, 153, 153));

        lb_anggota.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_anggota.setForeground(new java.awt.Color(51, 51, 51));
        lb_anggota.setText("ANGGOTA");

        lb_jumlahAnggota.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lb_jumlahAnggota.setForeground(new java.awt.Color(51, 51, 51));
        lb_jumlahAnggota.setText("99");

        lb_iconAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N

        javax.swing.GroupLayout cardAnggotaLayout = new javax.swing.GroupLayout(cardAnggota);
        cardAnggota.setLayout(cardAnggotaLayout);
        cardAnggotaLayout.setHorizontalGroup(
            cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggotaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_anggota)
                    .addComponent(lb_jumlahAnggota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(lb_iconAnggota)
                .addGap(20, 20, 20))
        );
        cardAnggotaLayout.setVerticalGroup(
            cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggotaLayout.createSequentialGroup()
                .addGroup(cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardAnggotaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lb_iconAnggota))
                    .addGroup(cardAnggotaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_anggota)
                        .addGap(20, 20, 20)
                        .addComponent(lb_jumlahAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        cardAnggota3.setBackground(new java.awt.Color(153, 153, 153));

        lb_anggota3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_anggota3.setForeground(new java.awt.Color(51, 51, 51));
        lb_anggota3.setText("PENGEMBALIAN");

        lb_jumlahAnggota3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lb_jumlahAnggota3.setForeground(new java.awt.Color(51, 51, 51));
        lb_jumlahAnggota3.setText("99");

        lb_iconAnggota3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N

        javax.swing.GroupLayout cardAnggota3Layout = new javax.swing.GroupLayout(cardAnggota3);
        cardAnggota3.setLayout(cardAnggota3Layout);
        cardAnggota3Layout.setHorizontalGroup(
            cardAnggota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(cardAnggota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardAnggota3Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(lb_anggota3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_iconAnggota3))
                    .addComponent(lb_jumlahAnggota3))
                .addContainerGap())
        );
        cardAnggota3Layout.setVerticalGroup(
            cardAnggota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cardAnggota3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardAnggota3Layout.createSequentialGroup()
                        .addComponent(lb_anggota3)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardAnggota3Layout.createSequentialGroup()
                        .addComponent(lb_iconAnggota3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(lb_jumlahAnggota3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("Dashboard");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Riwayat Peminjaman Buku");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard.png"))); // NOI18N

        cardAnggota4.setBackground(new java.awt.Color(153, 153, 153));

        lb_anggota4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_anggota4.setForeground(new java.awt.Color(51, 51, 51));
        lb_anggota4.setText("PEMINJAMAN");

        lb_jumlahAnggota4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lb_jumlahAnggota4.setForeground(new java.awt.Color(51, 51, 51));
        lb_jumlahAnggota4.setText("99");

        lb_iconAnggota4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N

        javax.swing.GroupLayout cardAnggota4Layout = new javax.swing.GroupLayout(cardAnggota4);
        cardAnggota4.setLayout(cardAnggota4Layout);
        cardAnggota4Layout.setHorizontalGroup(
            cardAnggota4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(cardAnggota4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardAnggota4Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(lb_anggota4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_iconAnggota4))
                    .addComponent(lb_jumlahAnggota4))
                .addContainerGap())
        );
        cardAnggota4Layout.setVerticalGroup(
            cardAnggota4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cardAnggota4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardAnggota4Layout.createSequentialGroup()
                        .addComponent(lb_anggota4)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardAnggota4Layout.createSequentialGroup()
                        .addComponent(lb_iconAnggota4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(lb_jumlahAnggota4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        cardAnggota5.setBackground(new java.awt.Color(153, 153, 153));

        lb_anggota5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_anggota5.setForeground(new java.awt.Color(51, 51, 51));
        lb_anggota5.setText("DAFTAR BUKU");

        lb_jumlahAnggota5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lb_jumlahAnggota5.setForeground(new java.awt.Color(51, 51, 51));
        lb_jumlahAnggota5.setText("99");

        lb_iconAnggota5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N

        javax.swing.GroupLayout cardAnggota5Layout = new javax.swing.GroupLayout(cardAnggota5);
        cardAnggota5.setLayout(cardAnggota5Layout);
        cardAnggota5Layout.setHorizontalGroup(
            cardAnggota5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(cardAnggota5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardAnggota5Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(lb_anggota5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_iconAnggota5))
                    .addComponent(lb_jumlahAnggota5))
                .addContainerGap())
        );
        cardAnggota5Layout.setVerticalGroup(
            cardAnggota5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cardAnggota5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardAnggota5Layout.createSequentialGroup()
                        .addComponent(lb_anggota5)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardAnggota5Layout.createSequentialGroup()
                        .addComponent(lb_iconAnggota5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(lb_jumlahAnggota5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cardAnggota5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cardAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cardAnggota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cardAnggota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardAnggota3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardAnggota4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardAnggota5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardAnggota;
    private javax.swing.JPanel cardAnggota3;
    private javax.swing.JPanel cardAnggota4;
    private javax.swing.JPanel cardAnggota5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_anggota;
    private javax.swing.JLabel lb_anggota3;
    private javax.swing.JLabel lb_anggota4;
    private javax.swing.JLabel lb_anggota5;
    private javax.swing.JLabel lb_iconAnggota;
    private javax.swing.JLabel lb_iconAnggota3;
    private javax.swing.JLabel lb_iconAnggota4;
    private javax.swing.JLabel lb_iconAnggota5;
    private javax.swing.JLabel lb_jumlahAnggota;
    private javax.swing.JLabel lb_jumlahAnggota3;
    private javax.swing.JLabel lb_jumlahAnggota4;
    private javax.swing.JLabel lb_jumlahAnggota5;
    // End of variables declaration//GEN-END:variables
}
